---
- name: Charts Version Rename
  lineinfile:
    dest: "/tmp/k8s-charts/ndap/{{ items }} "
    regexp: '^version:'
    line: 'version: {{ charts_version }}'
    state: present
  with_items:
    - ndap-conductor-server
    - ndap-conductor-worker
    - ndap-docs
    - ndap-elasticsearch
    - ndap-gateway
    - ndap-hive-metastore
    - ndap-hive-metastore-init-db
    - ndap-init-db
    - ndap-init-token
    - ndap-kyuubi-server
    - ndap-kyuubi-sparksql-remover
    - ndap-kyuubi-sparkjob-remover
    - ndap-mariadb
    - ndap-mgmt
    - ndap-ranger-admin
    - ndap-ranger-init-repo
    - ndap-solr
    - ndap-solr-operator
    - ndap-spark-historyserver
    - ndap-storage
    - ndap-trino-operator
    - ndap-trino
    - ndap-web
    - ndap-workbench
    - ndap-workflow
    - ndap-zookeeper

- name: "App Version Rename: ndap-conductor-server"
    lineinfile:
      dest: "/tmp/k8s-charts/ndap/{{ items }} "
      regexp: '^appVersion:'
      line: 'appVersion: {{ charts_version }}'
      state: present
    with_items:
